Dev
CHern0g0r/graphabase pull request #2
Opened 2020-03-04 22:31 UTC by CHern0g0r

2020-03-05 13:31 UTC, gsvgit requested changes

2020-03-05 13:31 UTC, gsvgit commented on test/test_dfa.py
> +def test_nfa_intersection():
А можно ли пересечь ДКА с НКА не детерминизируя НКА? В нашем случае ДКА --- это запрос, а НКА --- это база данных.

2020-03-05 13:31 UTC, gsvgit commented on test/test_dfa.py
> +def test_regex_to_min_dfa():
А чем отличаются этот тест и следующий? DFA --- это же просто обёртка и Вы одни и те же методы вызываете. Разве нет?

2020-03-05 13:31 UTC, gsvgit commented on test/test_dfa.py
> +    regex = Regex("(a-|a a b)*")
А что за магическй символ перед альтернативой? Нам нужны сейчас классические регулярные выражения.

2020-03-05 13:31 UTC, gsvgit commented on src/rdf_utils.py
> +import rdflib
А это имеемт отношение ко второй задаче?

2020-03-05 13:31 UTC, gsvgit commented on README.md
> +
А как всё это установить у себя?

2020-03-05 15:11 UTC, CHern0g0r commented on test/test_dfa.py
> +def test_regex_to_min_dfa():
Мы тестим преобразование сырой строки в регексп и из нее в ДКА

2020-03-06 10:59 UTC, CHern0g0r commented
Я забыл, что реквест надо реревьюить

2020-03-08 14:36 UTC, gsvgit approved these changes
Первый и последний раз прощаю наличие кода не имеющего отношения к сдаваемой задаче.

2020-03-08 17:14 UTC, merged