Add new cfg2cnf
CHern0g0r/graphabase pull request #5
Opened 2020-03-27 01:46 UTC by CHern0g0r

Добавил исправления по предыдущим претензиям

2020-03-27 06:37 UTC, gsvgit requested changes

2020-03-27 06:37 UTC, gsvgit commented on test/test_cfg.py
> +    c = CFG()
Тестировать нужно в разных тестах независимо разные функции. Так что отдельно чтение, отдельно печать.

2020-03-27 06:37 UTC, gsvgit commented on test/test_cfg.py
> +    assert(c.rule_right_part("asdf") == "asdf")
А что это за магические константы?

2020-03-29 15:21 UTC, CHern0g0r commented on test/test_cfg.py
> +    assert(c.rule_right_part("asdf") == "asdf")
Нам нужно в тестах использовать какие-то данные. Например такие.

2020-03-30 06:50 UTC, gsvgit approved these changes
Ок.

2020-03-30 15:21 UTC, merged